version: '{build}'
skip_tags: true
image: Visual Studio 2019
clone_depth: 3
environment:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  AWS_ACCESS_KEY_ID:
    secure: 7jhk0oV/vjFsOcsAHLMUcNGUGLuGmnuPxGH0ce/Vky8=
  AWS_SECRET_ACCESS_KEY:
    secure: 5KKYpsIHwYHHh5ud0U7Ss0rLumv6G8tkS6abh1B9aq4wY6+1kq5fN/3E5BsdBVKy
  AWS_DEFAULT_REGION: us-east-1
  S3_CONFIG_VOLATILE: --acl public-read --cache-control "public, must-revalidate, proxy-revalidate, max-age=0"
  GIT_FORMAT: '%%H'
  matrix:
  - ARCH: x64
    PLATFORM: x64
  - ARCH: x86
    PLATFORM: Win32
matrix:
  fast_finish: true
build_script:
- cmd: >-
    SET PATH=C:\Python37;%PATH%

    python utils/git-sync-deps

    mkdir build

    cd build

    cmake -G "Visual Studio 16 2019" -A %PLATFORM% -DSHADERC_ENABLE_SPVC=ON -DSHADERC_SKIP_INSTALL=ON -DSHADERC_SKIP_TESTS=ON ..

    cmake --build . --config Release

    aws s3 cp libshaderc\Release\shaderc_shared.dll s3://build.lwjgl.org/nightly/windows/%ARCH%/shaderc.dll %S3_CONFIG_VOLATILE%

    aws s3 cp libshaderc_spvc\Release\shaderc_spvc_shared.dll s3://build.lwjgl.org/nightly/windows/%ARCH%/shaderc_spvc.dll %S3_CONFIG_VOLATILE%

    cd ..

    git log --first-parent --pretty=format:%GIT_FORMAT% HEAD~2..HEAD~1 > revision.git

    aws s3 cp revision.git s3://build.lwjgl.org/nightly/windows/%ARCH%/shaderc.dll.git %S3_CONFIG_VOLATILE%
test: off
notifications:
- provider: Email
  to:
  - iotsakp@gmail.com
  subject: shaderc CI
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true